ca-cwds/CALS

- docker/app/ruby/dockerfile
Missed the line where we are using npm install in docker file.
Updated it to use yarn
> Dockerfile updated to use yarn for packages

- app/javascript/search/search.js
- #144644377
- sending cookies with fetch, so it honors authenticated session
- No
- No
-  N/A
- N/A
> sending cookies with fetch

- app/controllers/heartbeat_controller.rb
- app/views/heartbeat/show.html
- config/routes.rb
- spec/features/heartbeat/show_heartbeat_test_spec.rb
- #144495343
- heartbeat check page that bypasses authentication check
- No
- No
- 42%
- 45 -> 45
> heartbeat page

- app/classes/elastic/query_builder.rb
- spec/classes/elastic/query_builder_spec.rb
- Yes
- https://www.pivotaltracker.com/story/show/143904853
- Building elastic search query from search hash
- This story was marked as dependency on search facility page update. This will help to retrieve accurate search results
- no
- Spec 74%
- 21
> elasticsearch query builder

- app/views/layouts/application.html.erb
- config/application.rb
- config/initializers/session_store.rb
- N/A
- N/A
- Changing app name to reflect the project name
- No
- No
- N/A
- N/A
> changing app name to cals

- app/javascript/search/stylesheets/search.scss
-NA
-#145471745
- Dropdown having down arrow made clickable and can open dropdown list
-No
-npm run dev
- rspec - 100%, JS - 90.24%
- error => 1
> fix dropdown issue to open list

- config/application.rb
- N/A
- N/A
- Log to stdout. Forgot to setup logger. 
-
-
-
-
> Setting config.logger

- app/assets/stylesheets/shared/headers.scss
- app/javascript/search/search.js
- app/javascript/search/search_Data.js
- app/javascript/search/search_grid.js
- app/javascript/search/search_input.js
- app/javascript/search/search_notfount.js
- app/javascript/search/stylesheets/search.scss
- app/models/facility.rb
- config/environments/aws_dev.rb
- config/environments/development.rb
- config/webpack/configuration.js
- config/webpack/paths.yml
-n/a
- #146335961
-Public assets path change
-no
- no
- no
- no
> Public assets path

- config/webpack/test.js
- N/A
- Karma report wasn't generating properly. This fixes it. 
-
- No
- N/A
- 0
> missed update to webpacker test config to generate karma reprots

- spec/cassettes/cals_base_controller/facilities_controller_set_session_token_should_token_if_token_is_empty.yml
- spec/controllers/cals_base_controller_spec.rb
- spec/controllers/facilities_controller_spec.rb
- n/a
-#146720813
- refactor cals base controller spec separately, so its not part of facilities controller spec.
- no
- n/a
-100%
-n/a
> refactor cals base controller spec

- bin/server
- config/application.rb
- config/environments/development.rb
- config/webpacker.yml
- https://www.pivotaltracker.com/story/show/146877909
- app doesn't function when deployed in sub-directory
- Yes, application doesn't function in pre-int
- No
- n/a
- 0
> configuring app for sub-directory deploy

- app/javascript/common/dropDownField.js
- app/javascript/common/nameCardField.js
- app/javascript/common/phoneNumberField.js
- app/javascript/forms/cardsMain.jsx
- app/javascript/forms/stylesheets/cards-main.scss
- yes
- #146344381
- Applicant card with name, employment and more details
- NA
- npm run dev
-JS -> 80
- 93
> clear phone type fix & blue border highlight fix

- app/javascript/common/dropDownField.js
- app/javascript/common/nameCardField.js
- app/javascript/common/phoneNumberField.js
- app/javascript/forms/cardsMain.jsx
- app/javascript/forms/residenceCardsMain.jsx
- app/javascript/forms/stylesheets/cards-main.scss
> Phone card fix

- docker/dev/app/cals/dockerfile
Adding new api env vars so tests can pass when building app container.
> Docker build - adding new env var

- public/example.jsx
- as discussed, here is an example react file that goes over the react lifecycle , and it's methods and usage.
- n/a gets us better at react
- an example file to help us get better at react
- no
-no
- n/a
- n/a
> example react lifecycle file in public directory

- app/javascript/forms/applicantCard.jsx
- app/javascript/forms/applicantCardsGroup.jsx
- app/javascript/forms/employmentCard.jsx
- app/javascript/forms/index.js
- app/javascript/forms/nameCard.js
- app/javascript/forms/phoneNumberCardsGroup.jsx
- No
- https://www.pivotaltracker.com/story/show/146344381
- Applicant card showing same data as applicant 1 when 2nd one is added
- same
- same
> Applicant data repeated issue

- app/javascript/search/common/commonUtils.js
- config/karma.conf.js
- spec/cassettes/facilities/find_facilties_by_entering_facility_id.yml
- test/javascript/facility/address_tests.js
- test/javascript/facility/children_tests.js
- test/javascript/facility/facilityComplaints_tests.js
- test/javascript/facility/innerBlockAddressTitles_tests.js
-https://osi-cwds.atlassian.net/browse/CALS-5464
-Changed Address format to Street, City and State xxxxx
-Change phone format to (xxx) xxx-xxxx
-No
-No
statements: 80,
branches: 67,
functions: 76,
lines: 81
> CALS-5464-format facility address and phone

- app/javascript/rfa_forms/rfa01a_edit_view/nameCard.js
- test/javascript/rfa_forms/rfa01a_edit_view/nameCard_tests.js
https://osi-cwds.atlassian.net/browse/CALS-5427
Add Another Name button in RFA 1A changed to Add Alias
No
No
No
> CALS2-5427: Add Another Name button in RFA 1A changed to Add Alias

- docker/dev/app/cals/dockerfile
- https://osi-cwds.atlassian.net/browse/DOE-2637
> DOE-2637 updated cals directory path

- spec/acceptance/facilities/show_facility_test_spec.rb
- spec/features/facilities/show_facility_spec.rb
- https://osi-cwds.atlassian.net/browse/CALS-5948
- Acceptance tests updated to read 'phone number'
> CALS-5948 Facility acceptance test update for phone number column header

- app/javascript/components/common/pageTemplate.js
- https://osi-cwds.atlassian.net/browse/AARA-169
- hotfix to wrap back to dashboard in cals url
-no
-no
-n/a
> AARA-169: hotfix for url prefix to add cals

- app/javascript/components/common/rfaListPageHeaderButtons.js
- https://osi-cwds.atlassian.net/browse/AARA-241
- Minor text change. This story was previously approved and deployed in this pr: https://github.com/ca-cwds/CALS/pull/475
- no
- no
- NA
> AARA-241 Header page for RFA Application List

- app/javascript/rfa_forms/tracking/tableRows/familyDocRow.js
- AARA-426 
-hotfix for cancel doesn't work on family doc links for cancel
-
-
-
> fix broken checkbox on family doc

- app/javascript/components/common/pageHeader.js
- app/javascript/components/common/pageTemplate.js
- app/javascript/components/common/rfa01PageHeaderButtons.js
- app/javascript/components/common/rfaListPageHeaderButtons.js
- app/javascript/rfa_forms/rfa01a_list/index.js
- https://osi-cwds.atlassian.net/browse/AARA-385
-  RFA list view page header buttons to fit within pageheader
- NA
- NA
- NA
> AARA-385:  Buttons extend beyond page header when display resolution is not at maximum

- app/javascript/rfa_forms/rfa01a_edit_view/aboutApplicantCard.jsx
- spec/acceptance/rfa_forms/rfa_01a_application_spec.rb
- spec/acceptance/rfa_forms/rfa_01b_application_spec.rb
- spec/acceptance/rfa_forms/rfa_01c_application_spec.rb
- test/javascript/rfa_forms/rfa01a_edit_view/aboutApplicantCard_tests.js
- https://osi-cwds.atlassian.net/browse/AARA-431
- Applicant gender field should be marked as required
- No
- No
- NA
> AARA_431 Applicant gender field should be marked as required

- package.json
- yarn.lock
- Fixes responsiveness for global header. Both Profile name and CWDS text will in one line.
> update React-wood-duck version to 0.1.79

- spec/rails_helper.rb
- https://osi-cwds.atlassian.net/browse/FIT-359
- Fix for Smoke test on Integration
-
> Fix for cognito not to kick the user out from cals page

- Jenkinsfile
- spec/rails_helper.rb
- https://osi-cwds.atlassian.net/browse/FIT-359
- Successfully Tested on a test Jenkins job
http://jenkins.mgmt.cwds.io:8080/job/PreInt-Integration/job/cals-app-pre-int-testing/
-
> FIT-359-Final touch down for smoke test on Integration with success

- Jenkinsfile
applied the new shared library for code quality checks
used the shared library to build docker test container so that lint() from shared library will work
this should not affect other tests that use the same docker test container 
[Apply the new shared library for code quality checks](https://osi-cwds.atlassian.net/browse/FIT-404)
Change in jenkinsfile only, no tests required
> FIT-404 Apply the new shared library for code quality checks

- app/javascript/search/common/commonUtils.js
- app/javascript/selectors/facilityDataSelectors.js
- app/models/facility.rb
- bin/hack-to-copy-fonts.sh
- test/javascript/search/common/commonUtils_tests.js
- test/javascript/selectors/facilityDataSelectors_tests.js
SEAR-83: License Effective Date not displaying on County-Licensed Facilities
-https://osi-cwds.atlassian.net/browse/SEAR-83
-Added the logic such that:
If facility source is LIS, display license effective date all the times
If facility source is CWS/CMS, display license effective date only for Licensed or RFA Approved statuses. 
-No
> SEAR-83: License Effective Date not displaying on County-Licensed Facilities
